AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Creates all necessary DNS resources in the Shared Signals account

Parameters:
  Environment:
    Description: Name of Environment to deploy to
    Type: String
    AllowedValues:
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals
    - !Ref Environment
    - production
  MockReceiverCustomDomain: !Or
    - !Equals [!Ref Environment, staging]
    - !Equals [!Ref Environment, build]

Resources:

  SignalExchangeHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - signal-exchange.account.gov.uk
        - !Sub 'signal-exchange.${Environment}.account.gov.uk'

  ##################
  # Mock Receiver  #
  ##################

  SharedSignalsMockReceiverApiPublicHostedZone:
    Condition: MockReceiverCustomDomain
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'


  ###############
  #  Transmitter  #
  ###############

  SharedSignalsTransmitterApiPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - transmitter.signal-exchange.account.gov.uk
        - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'


  ###############################
  # Transmitter Cognito User Pool  #
  ################################

  SharedSignalsTransmitterCognitoPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - auth.transmitter.signal-exchange.account.gov.uk
        - !Sub 'auth.transmitter.signal-exchange.${Environment}.account.gov.uk'

#  SharedSignalsTransmitterApiCertificate:
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: !If
#        - IsProduction
#        - transmitter.signal-exchange.account.gov.uk
#        - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'
#      DomainValidationOptions:
#        - DomainName: !If
#            - IsProduction
#            - transmitter.signal-exchange.account.gov.uk
#            - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'
#          HostedZoneId: !GetAtt SharedSignalsTransmitterApiPublicHostedZone.Id
#      ValidationMethod: DNS
#
#  SharedSignalsMockReceiverApiCertificate:
#    Condition: MockReceiverCustomDomain
#    DependsOn: SignalExchangeMockReceiverDnsDelegation
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'
#      DomainValidationOptions:
#        - DomainName: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'
#          HostedZoneId: !GetAtt SharedSignalsMockReceiverApiPublicHostedZone.Id
#      ValidationMethod: DNS


#  SignalExchangeMockReceiverDnsDelegation:
#    Condition: MockReceiverCustomDomain
#    Type: AWS::Route53::RecordSet
#    Properties:
#      HostedZoneId: !GetAtt SignalExchangeHostedZone.Id
#      Name: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'
#      ResourceRecords: !GetAtt SharedSignalsMockReceiverApiPublicHostedZone.NameServers
#      TTL: '300'
#      Type: NS
