AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Creates all necessary DNS resources in the Shared Signals account

Parameters:
  Environment:
    Description: Name of Environment to deploy to
    Type: String
    AllowedValues:
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals
    - !Ref Environment
    - production
  MockReceiverCustomDomain: !Or
    - !Equals [!Ref Environment, staging]
    - !Equals [!Ref Environment, build]

Resources:

  SignalExchangeHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - signal-exchange.account.gov.uk
        - !Sub 'signal-exchange.${Environment}.account.gov.uk'

  ##################
  # Mock Receiver  #
  ##################

  SharedSignalsMockReceiverApiPublicHostedZone:
    Condition: MockReceiverCustomDomain
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'

  SignalExchangeMockReceiverDnsDelegation:
    Condition: MockReceiverCustomDomain
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !GetAtt SignalExchangeHostedZone.Id
      Name: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'
      ResourceRecords: !GetAtt SharedSignalsMockReceiverApiPublicHostedZone.NameServers
      TTL: '300'
      Type: NS

  SharedSignalsMockReceiverApiCertificate:
    Condition: MockReceiverCustomDomain
    DependsOn: SignalExchangeMockReceiverDnsDelegation
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'
      DomainValidationOptions:
        - DomainName: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'
          HostedZoneId: !GetAtt SharedSignalsMockReceiverApiPublicHostedZone.Id
      ValidationMethod: DNS

  SharedSignalsMockReceiverApiDomainName:
    Condition: MockReceiverCustomDomain
    Type: AWS::ApiGateway::DomainName
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002  # Required as EndpointAccessMode gets flagged as "Additional property not allowed" which means that cfn-lint does not recognise this property as valid even though it is, this is possibly a fairly new property added that cfn-lint has not been able to update its validation schema.
    Properties:
      DomainName: !Sub 'mock-receiver.signal-exchange.${Environment}.account.gov.uk'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref SharedSignalsMockReceiverApiCertificate
      SecurityPolicy: SecurityPolicy_TLS13_1_2_PQ_2025_09
      EndpointAccessMode: BASIC  # STRICT may be too restrictive however with BASIC we already have DisableExecuteApiEndpoint: true

  SharedSignalsMockReceiverApiDomainNameParameter:
    Condition: MockReceiverCustomDomain
    Type: AWS::SSM::Parameter
    Properties:
      Name: MockReceiverApiDomainName
      Type: String
      Value: !Ref SharedSignalsMockReceiverApiDomainName
  ###############
  #  Transmitter  #
  ###############

  SharedSignalsTransmitterApiPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - transmitter.signal-exchange.account.gov.uk
        - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'

  SignalExchangeTransmitterDnsDelegation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !GetAtt SignalExchangeHostedZone.Id
      Name: !If
        - IsProduction
        - transmitter.signal-exchange.account.gov.uk
        - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'
      ResourceRecords: !GetAtt SharedSignalsTransmitterApiPublicHostedZone.NameServers
      TTL: '300'
      Type: NS

  SharedSignalsTransmitterApiCertificate:
    DependsOn: SignalExchangeTransmitterDnsDelegation
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - IsProduction
        - transmitter.signal-exchange.account.gov.uk
        - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'
      DomainValidationOptions:
        - DomainName: !If
            - IsProduction
            - transmitter.signal-exchange.account.gov.uk
            - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'
          HostedZoneId: !GetAtt SharedSignalsTransmitterApiPublicHostedZone.Id
      ValidationMethod: DNS

  SharedSignalsTransmitterApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002 # Required as EndpointAccessMode gets flagged as "Additional property not allowed" which means that cfn-lint does not recognise this property as valid even though it is, this is possibly a fairly new property added that cfn-lint has not been able to update its validation schema.
    Properties:
      DomainName: !If
        - IsProduction
        - transmitter.signal-exchange.account.gov.uk
        - !Sub 'transmitter.signal-exchange.${Environment}.account.gov.uk'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref SharedSignalsTransmitterApiCertificate
      SecurityPolicy: SecurityPolicy_TLS13_1_2_PQ_2025_09
      EndpointAccessMode: BASIC

  SharedSignalsTransmitterApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: TransmitterApiDomainName
      Type: String
      Value: !Ref SharedSignalsTransmitterApiDomainName
  ###############################

  # Transmitter Cognito User Pool  #
  ################################

  SharedSignalsTransmitterCognitoPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !If
        - IsProduction
        - auth.transmitter.signal-exchange.account.gov.uk
        - !Sub 'auth.transmitter.signal-exchange.${Environment}.account.gov.uk'

  SignalExchangeTransmitterCognitoDnsDelegation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !GetAtt SignalExchangeHostedZone.Id
      Name: !If
        - IsProduction
        - auth.transmitter.signal-exchange.account.gov.uk
        - !Sub 'auth.transmitter.signal-exchange.${Environment}.account.gov.uk'
      ResourceRecords: !GetAtt SharedSignalsTransmitterCognitoPublicHostedZone.NameServers
      TTL: '300'
      Type: NS

Outputs:
  SignalExchangeHostedZoneId:
    Value: !GetAtt SignalExchangeHostedZone.Id
    Export:
      Name: SignalExchangeHostedZoneId
