name: Publish DNS Shared Signals template to main

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/dns-olse-outbound/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  package:
    name: Package template
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Setup Python 3.8
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310  # v3
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885  # v6.1.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.DNS_SHARED_SIGNALS_GH_ACTIONS_ROLE_ARN }}
      - name: Package SAM app
        uses: govuk-one-login/devplatform-upload-action@5879c30205266ad61e8299a4fcea76364530c9c1  # v3.14.0
        with:
          artifact-bucket-name: ${{ secrets.DNS_SHARED_SIGNALS_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.DNS_SHARED_SIGNALS_SIGNING_PROFILE_NAME }}
          template-file: infrastructure/dns-olse-outbound/template.yaml
          working-directory: .
