name: Publish DNS Shared Signals template to main

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/dns-olse-outbound/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  package:
    name: Package template
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Setup Python 3.8
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310  # v3
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b  # v6.2.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.DNS_SHARED_SIGNALS_GH_ACTIONS_ROLE_ARN }}
      - name: Package SAM app
        uses: govuk-one-login/devplatform-upload-action@64e46134b4108ebfa1cf2a64fee00782f8e2e8cf  # v4.1.0
        with:
          artifact-bucket-name: ${{ secrets.DNS_SHARED_SIGNALS_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.DNS_SHARED_SIGNALS_SIGNING_PROFILE_NAME }}
          template-file: infrastructure/dns-olse-outbound/template.yaml
          working-directory: .
