name: Validate & lint templates

on: push

jobs:
  validate-templates:
    name: Validate SAM templates
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Setup Python 3.8
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310  # v3
      - name: Validate SAM templates
        run: ./scripts/validate-templates.sh
      - name: Run Checkov on SAM templates
        uses: bridgecrewio/checkov-action@4048c972aae68d0b983a48bb3479aab2d877b898  # v12.3102.0
        with:
          directory: infrastructure/
          quiet: true
          framework: cloudformation
