name: Validate & lint templates

on: push

jobs:
  validate-templates:
    name: Validate SAM templates
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Setup Python 3.8
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310  # v3
      - name: Validate SAM templates
        run: ./scripts/validate-templates.sh
      - name: Run Checkov on SAM templates
        uses: bridgecrewio/checkov-action@4a1afa9897f7afe297a3762c926e1e800361464f  # v12.3111.0
        with:
          directory: infrastructure/
          quiet: true
          framework: cloudformation
