name: Validate & lint templates

on: push

jobs:
  validate-templates:
    name: Validate SAM templates
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Setup Python 3.8
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310  # v3
      - name: Validate SAM templates
        run: ./scripts/validate-templates.sh
      - name: Run Checkov on SAM templates
        uses: bridgecrewio/checkov-action@6772af193d58e46738c9401a4ca9c1f39de0fec8  # v12.3104.0
        with:
          directory: infrastructure/
          quiet: true
          framework: cloudformation
